teams:
  - name: caliper-admins
    maintainers:
      - aklenik
      - davidkel
  - name: caliper-committers
    maintainers:
      - aklenik
      - davidkel
  - name: staff
    maintainers:
      - ryjones
    members:
      - jwagantall
      - thelinuxfoundation
repositories:
  - name: governance
    teams:
      staff: maintain
    visibility: public
  - name: caliper
    teams:
      caliper-admins: admin
      caliper-committers: maintain
    visibility: public
  - name: caliper-benchmarks
    teams:
      caliper-admins: admin
      caliper-committers: maintain
    visibility: public
